# Change these first
owner: bbjprojek # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: BBJProjeK Documentation
    url: https://wiki.bbjprojek.org
  - name: bbjprojek Legacy Infrastructure
    url: https://kiwi.bbjprojek.org
  - name: BBJProjeK Blog
    url: https://blog.bbjprojek.org
  - name: BBJProjeK Email Service
    url: https://mail.bbjprojek.org
  - name: BBJProjeK CDN Server
    url: https://cdn.bbjprojek.org
  - name: Lapiacery Infrastructure
    url: https://lpry.bbjprojek.org
  - name: BBJProjeK Gitlab
    url: https://gitlab.bbjprojek.org
  - name: BBJProjeK Sub-Project Example
    url: https://wiki.bbjprojek.org/andenes

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.bbjprojek.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/bbjprojek/status/master/assets/status.svg
  name: BBJProjeK Status
  hideNavTitle: true
  introTitle: "**BBJProjeK** current status"
  introMessage: This status page uses **real-time** data from our [GitHub repository](https://github.com/bbjprojek/status).
  faviconSvg: https://raw.githubusercontent.com/bbjprojek/status/master/assets/favicon.svg
  favicon: https://raw.githubusercontent.com/bbjprojek/status/master/assets/favicon-32x32.png
  metaTags:
    - name: "description"
      content: "BBJProjeK Services Status"
    - name: "author"
      content: "bbjprojek labs"
    - name: "theme-color"
      content: "#008076"
    - property: "og:title"
      content: "BBJProjeK Server Status"
    - property: "og:descrition"
      content: "Services Status"
    - property: "og:url"
      content: "https://status.bbjprojek.org"
    - property: "og:type"
      content: "Website"
    - property: "og:image"
      content: "https://raw.githubusercontent.com/bbjprojek/status/master/assets/favicon_full.png"
  navbar:
    - title: Status
      href: /
    - title: GitLab
      href: https://gitlab.bbjprojek.org
  links:
    - rel: stylesheet
      href: assets/custom.css

  robotsText: "User-agent: * \n Allow: /"

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "* */4 * * *"
  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
