owner: bbjprojek
repo: status

sites:
  - name: BBJProjeK
    url: https://bbjprojek.org
  - name: BBJProjeK Documentation
    url: https://wiki. bbjprojek.org
  - name: BBJProjeK Mail
    url: https://mail.bbjprojek.org
  - name: BBJProjeK Git
    url: https://git.bbjprojek.org
  - name: BBJProjeK CDN Server
    url: https://get.cdn.bbjprojek.org
  - name: Lapiacery Infrastructure
    url: https://lapiacery.bbjprojek.org
  - name: BBJProjeK Cabinet & R2
    url: https://cabinet.bbjprojek.org
  - name: BBJProjeK Sub-Projects
    url: https://wiki.bbjprojek.org/andenes

status-website:
  cname: status.bbjprojek.org
  logoUrl: https://raw.githubusercontent.com/bbjprojek/status/master/assets/status.svg
  name: BBJProjeK Status
  hideNavTitle: true
  introTitle: "**BBJProjeK** current status"
  introMessage: This status page uses **real-time** data from our [GitHub repository](https://github.com/bbjprojek/status).
  faviconSvg: https://raw.githubusercontent.com/bbjprojek/status/master/assets/favicon.svg
  favicon: https://raw.githubusercontent.com/bbjprojek/status/master/assets/favicon-32x32.png
  metaTags:
    - name: "description"
      content: "BBJProjeK Services Status"
    - name: "author"
      content: "The BBJProjeK Organization"
    - name: "theme-color"
      content: "#1D4F91"
    - property: "og:title"
      content: "BBJProjeK Server Status"
    - property: "og:descrition"
      content: "Services Status"
    - property: "og:url"
      content: "https://status.bbjprojek.org"
    - property: "og:type"
      content: "Website"
    - property: "og:image"
      content: "https://raw.githubusercontent.com/bbjprojek/status/master/assets/favicon_full.png"
  navbar:
    - title: BBJProjeK
      href: https://bbbjprojek.org
    - title: Status
      href: /
  links:
    - rel: stylesheet
      href: assets/custom.css

  robotsText: "User-agent: * \n Allow: /"

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "* */4 * * *"
